-- Rivo background Web Push notifications
-- Run this after supabase_schema.sql.
-- The browser stores only public subscription material. Private VAPID keys
-- stay in Supabase Edge Function secrets.

create table if not exists public.rivo_push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null,
  p256dh text not null,
  auth text not null,
  user_agent text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, endpoint)
);

create index if not exists rivo_push_subscriptions_user_idx
  on public.rivo_push_subscriptions(user_id);

alter table public.rivo_push_subscriptions enable row level security;

drop policy if exists "rivo_push_subscriptions_select_own" on public.rivo_push_subscriptions;
create policy "rivo_push_subscriptions_select_own"
  on public.rivo_push_subscriptions for select to authenticated
  using (auth.uid() = user_id);

drop policy if exists "rivo_push_subscriptions_delete_own" on public.rivo_push_subscriptions;
create policy "rivo_push_subscriptions_delete_own"
  on public.rivo_push_subscriptions for delete to authenticated
  using (auth.uid() = user_id);

create or replace function public.rivo_save_push_subscription(
  p_endpoint text,
  p_p256dh text,
  p_auth text,
  p_user_agent text default ''
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare v_id bigint;
begin
  if auth.uid() is null then raise exception 'Not signed in'; end if;
  if coalesce(length(trim(p_endpoint)),0) < 20 then raise exception 'Invalid push endpoint'; end if;
  if coalesce(length(trim(p_p256dh)),0) < 20 then raise exception 'Invalid push key'; end if;
  if coalesce(length(trim(p_auth)),0) < 10 then raise exception 'Invalid push auth key'; end if;

  insert into public.rivo_push_subscriptions(user_id,endpoint,p256dh,auth,user_agent,updated_at)
  values(auth.uid(),trim(p_endpoint),trim(p_p256dh),trim(p_auth),left(coalesce(p_user_agent,''),500),now())
  on conflict (user_id,endpoint) do update
    set p256dh=excluded.p256dh,
        auth=excluded.auth,
        user_agent=excluded.user_agent,
        updated_at=now()
  returning id into v_id;

  return jsonb_build_object('id',v_id,'saved',true);
end;
$$;

revoke all on function public.rivo_save_push_subscription(text,text,text,text) from public;
grant execute on function public.rivo_save_push_subscription(text,text,text,text) to authenticated;

create or replace function public.rivo_remove_push_subscription(p_endpoint text)
returns boolean
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'Not signed in'; end if;
  delete from public.rivo_push_subscriptions
  where user_id=auth.uid() and endpoint=trim(p_endpoint);
  return true;
end;
$$;

revoke all on function public.rivo_remove_push_subscription(text) from public;
grant execute on function public.rivo_remove_push_subscription(text) to authenticated;
